/// \file Wind.hpp
/// \brief Atmospheric wind field: steady wind, boundary-layer shear and Dryden turbulence.
#pragma once

#include <Eigen/Dense>

#include "aether/core/Types.hpp"
#include "aether/util/Random.hpp"

namespace aether::env {

/// \brief Configuration of the wind and turbulence environment.
struct WindConfig {
  /// Steady wind velocity in NED at the reference altitude [m/s].
  Vec3 steady_ned = Vec3::Zero();

  /// Enable the logarithmic boundary-layer shear profile.
  bool enable_shear = true;
  /// Altitude at which `steady_ned` is specified [m AGL].
  double shear_reference_altitude = 50.0;
  /// Surface roughness length used by the logarithmic profile [m] (0.05 = open grassland).
  double shear_roughness = 0.05;

  /// Enable Dryden turbulence.
  bool enable_turbulence = true;
  /// Turbulence intensities \f$(\sigma_u,\sigma_v,\sigma_w)\f$ in the body frame [m/s].
  Vec3 sigma = Vec3(1.06, 1.06, 0.7);
  /// Dryden length scales \f$(L_u, L_v, L_w)\f$ [m].
  Vec3 length_scale = Vec3(200.0, 200.0, 50.0);
  /// If true, scale sigma/L with altitude using the MIL-F-8785C low-altitude model.
  bool altitude_scaled = true;
  /// Wind speed at 6 m (20 ft) used by the MIL-F-8785C low-altitude scaling [m/s].
  double w20 = 5.0;
};

/// \brief Wind model producing a total wind vector and its gust component.
///
/// The steady component is expressed in NED and optionally scaled by a logarithmic
/// boundary-layer profile. The gust component is generated by Dryden shaping filters
/// (MIL-F-8785C) expressed in **body axes**:
/// \f[
///   H_u(s)=\sigma_u\sqrt{\tfrac{2V_a}{L_u}}\frac{1}{s+V_a/L_u},\qquad
///   H_{v,w}(s)=\sigma\sqrt{\tfrac{3V_a}{L}}\frac{s+V_a/(\sqrt3 L)}{(s+V_a/L)^2}.
/// \f]
/// Each filter is realised in state-space and propagated with an **exact** discretisation
/// (Van Loan), so the stationary variance is \f$\sigma^2\f$ independently of the step size.
class WindModel {
 public:
  /// \param config Wind configuration.
  /// \param seed   Seed for the turbulence noise stream.
  WindModel(const WindConfig& config, std::uint64_t seed);

  /// Advance the turbulence filters by \a dt seconds at airspeed \a airspeed and
  /// altitude \a altitude_agl (used for MIL-F-8785C scaling).
  /// \param dt Step [s], must be > 0.
  /// \param airspeed True airspeed [m/s] (clamped away from zero internally).
  /// \param altitude_agl Height above ground [m].
  void step(double dt, double airspeed, double altitude_agl);

  /// Steady + shear wind in NED at the given height above ground [m/s].
  Vec3 steadyNed(double altitude_agl) const;

  /// Current gust velocity in **body** axes [m/s].
  const Vec3& gustBody() const { return gust_body_; }

  /// Total wind in NED given the current attitude (steady + shear + gust) [m/s].
  /// \param q_nb Attitude quaternion (body to NED).
  /// \param altitude_agl Height above ground [m].
  Vec3 totalNed(const Vec4& q_nb, double altitude_agl) const;

  /// Reset the turbulence filter states to zero.
  void reset();

  /// Access the configuration in use.
  const WindConfig& config() const { return cfg_; }

 private:
  void updateScaling(double altitude_agl);

  WindConfig cfg_;
  util::Rng rng_;
  Vec3 gust_body_ = Vec3::Zero();

  // Filter states: u-axis is first order (1 state); v and w axes are second order (2 states).
  Eigen::Matrix<double, 1, 1> xu_ = Eigen::Matrix<double, 1, 1>::Zero();
  Eigen::Vector2d xv_ = Eigen::Vector2d::Zero();
  Eigen::Vector2d xw_ = Eigen::Vector2d::Zero();

  Vec3 sigma_eff_ = Vec3::Zero();
  Vec3 length_eff_ = Vec3::Zero();
};

}  // namespace aether::env
